#ifndef __FLASHDRV__
#define __FLASHDRV__
#define FLASHDRV_GEN_RAND 25084

#define FLASHDRV_NUMBLOCKS 1
#define FLASHDRV_DECRYPTVALUE   0xCC
#define FLASHDRV_DECRYPTDATA(a)   (vuint8)((vuint8)(a) ^ (vuint8)FLASHDRV_DECRYPTVALUE)
#define FLASHDRV_BLOCK0_ADDRESS   0xFEDF8000
#define FLASHDRV_BLOCK0_LENGTH   0x2500
#define FLASHDRV_BLOCK0_CHECKSUM   0x8B20u

#define FLASH_DRIVER_START_SEC_CONST
#include "memmap.hpp"
extern V_MEMROM0 V_MEMROM1  vuint8 V_MEMROM2 flashDrvBlk0[FLASHDRV_BLOCK0_LENGTH];
#define FLASH_DRIVER_STOP_SEC_CONST
#include "memmap.hpp"

#endif

